### PR TITLE
add default HC value

### PR DESCRIPTION
**Pull request by berancad**
add default HC value to docker-compose file help for users on Windows system (HC=1 docker compose up - syntax not working from cmd shell)

I hereby agree to the terms of the CLA available at: [link](https://yandex.ru/legal/cla/?lang=en).

### CODE REVIEW

**Review by Konstantin-Roumas — APPROVED** [review]

**Comment by resure** [comment]
Thank you for PR. Can you please add your consent to our CLA agreement in the PR description? You can read about it here: https://github.com/datalens-tech/datalens/blob/main/CONTRIBUTING.md

Speaking of PR itself: default value for HC should be set `0`, not `1`.

**Comment by berancad** [comment]
> Thank you for PR. Can you please add your consent to our CLA agreement in the PR description? You can read about it here: https://github.com/datalens-tech/datalens/blob/main/CONTRIBUTING.md

Added to first post.
> 
> Speaking of PR itself: default value for HC should be set `0`, not `1`.
I set value '1' because this value described in [readme.md](https://github.com/datalens-tech/datalens/blob/main/README.md).
1 - for Highcharts usage (more charts etc.). May be it is default for first start of datalens?

**Comment by resure** [comment]
> May be it is default for first start of datalens?

That would be logical and useful, but we need to have highcharts enabled only if user explicitly specified that with some option (HC=1 in our case), because highcharts itself have some licensing restrictions even for open source projects (more on that in README, "Notice on Highcharts usage")

That's why we are actively working on completely replacing highcharts with d3, so we would be able to drop that option altogether and live a simpler life :)

But for now default value needs to be off (`0`)

**Comment by berancad** [comment]
> > May be it is default for first start of datalens?
> 
> That would be logical and useful, but we need to have highcharts enabled only if user explicitly specified that with some option (HC=1 in our case), because highcharts itself have some licensing restrictions even for open source projects (more on that in README, "Notice on Highcharts usage")
> 
> That's why we are actively working on completely replacing highcharts with d3, so we would be able to drop that option altogether and live a simpler life :)
> 
> But for now default value needs to be off (`0`)

Ok, add another commit for set default HC value to 0

**Review by resure — APPROVED** [review]

**Pull request merged**
